// ============================================================
// MITRA-DASH PWA — Service Worker
// Generated by TNCF TEMANGGUNG GAS-to-PWA Converter
// ============================================================

const CACHE_NAME = 'mitra-dash-v1.0.0';
const GAS_URL = 'https://script.google.com/macros/s/AKfycbw-4qhpEP-4L050wX4IclvaFiPRvgo5Y09ukaZxi8dce1No3iW50pFKRYOLtBzqSByQ/exec';
const SYNC_TAG = 'sync-mitra-dash-queue';

// Static assets to pre-cache
const STATIC_ASSETS = [
  './index.html',
  './manifest.json',
  './icons/icon-192.svg',
  './icons/icon-512.svg',
  'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css',
  'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css',
  'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js',
  'https://cdn.jsdelivr.net/npm/sweetalert2@11',
  'https://cdn.jsdelivr.net/npm/chart.js',
  'https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js'
];

// ── INSTALL ──────────────────────────────────────────────
self.addEventListener('install', function(event) {
  console.log('[SW] Install — MITRA-DASH v1.0.0');
  event.waitUntil(
    caches.open(CACHE_NAME).then(function(cache) {
      return cache.addAll(
        STATIC_ASSETS.filter(function(url) {
          // Only pre-cache same-origin and trusted CDNs; skip potential failures gracefully
          return true;
        })
      ).catch(function(err) {
        console.warn('[SW] Some assets failed to pre-cache:', err);
      });
    }).then(function() {
      return self.skipWaiting();
    })
  );
});

// ── ACTIVATE ─────────────────────────────────────────────
self.addEventListener('activate', function(event) {
  console.log('[SW] Activate — clearing old caches');
  event.waitUntil(
    caches.keys().then(function(cacheNames) {
      return Promise.all(
        cacheNames.filter(function(name) {
          return name !== CACHE_NAME;
        }).map(function(name) {
          console.log('[SW] Deleting old cache:', name);
          return caches.delete(name);
        })
      );
    }).then(function() {
      return self.clients.claim();
    })
  );
});

// ── FETCH (Cache First with Network Fallback) ─────────────
self.addEventListener('fetch', function(event) {
  var url = event.request.url;

  // Pass through POST requests (GAS mutations) — don't cache them
  if (event.request.method !== 'GET') {
    return;
  }

  // For GAS URL GET requests (data fetch) — Network First, cache result
  if (url.includes('script.google.com')) {
    event.respondWith(
      fetch(event.request.clone(), { mode: 'cors' })
        .then(function(response) {
          if (response && response.status === 200) {
            var responseClone = response.clone();
            caches.open(CACHE_NAME).then(function(cache) {
              cache.put(event.request, responseClone);
            });
          }
          return response;
        })
        .catch(function() {
          console.log('[SW] Offline — serving GAS data from cache');
          return caches.match(event.request).then(function(cached) {
            if (cached) return cached;
            return new Response(
              JSON.stringify({ success: false, offline: true, message: 'Anda sedang offline. Data terakhir mungkin tidak tersedia.' }),
              { headers: { 'Content-Type': 'application/json' } }
            );
          });
        })
    );
    return;
  }

  // Cache First for everything else (static assets, CDN)
  event.respondWith(
    caches.match(event.request).then(function(cached) {
      if (cached) {
        // Background revalidate for CDN assets
        var networkFetch = fetch(event.request).then(function(response) {
          if (response && response.status === 200) {
            caches.open(CACHE_NAME).then(function(cache) {
              cache.put(event.request, response.clone());
            });
          }
          return response;
        }).catch(function() {});
        return cached;
      }

      return fetch(event.request).then(function(response) {
        if (!response || response.status !== 200 || response.type === 'opaque') {
          return response;
        }
        var responseClone = response.clone();
        caches.open(CACHE_NAME).then(function(cache) {
          cache.put(event.request, responseClone);
        });
        return response;
      }).catch(function() {
        // Fallback for navigation requests
        if (event.request.destination === 'document') {
          return caches.match('./index.html');
        }
      });
    })
  );
});

// ── BACKGROUND SYNC ──────────────────────────────────────
self.addEventListener('sync', function(event) {
  if (event.tag === SYNC_TAG) {
    console.log('[SW] Background sync triggered:', SYNC_TAG);
    event.waitUntil(processSyncQueue());
  }
});

async function processSyncQueue() {
  // Read queue from clients via postMessage pattern
  // Actual queue processing is handled in app.js
  // SW just notifies clients to process
  const allClients = await self.clients.matchAll({ includeUncontrolled: true });
  allClients.forEach(function(client) {
    client.postMessage({ type: 'BACKGROUND_SYNC_TRIGGERED', tag: SYNC_TAG });
  });
}

// ── PUSH NOTIFICATIONS (future-ready) ────────────────────
self.addEventListener('push', function(event) {
  var data = {};
  try { data = event.data.json(); } catch(e) {}
  var title = data.title || 'MITRA-DASH';
  var options = {
    body: data.body || 'Ada pembaruan baru.',
    icon: './icons/icon-192.svg',
    badge: './icons/icon-192.svg',
    vibrate: [100, 50, 100]
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

// ── MESSAGE HANDLER ───────────────────────────────────────
self.addEventListener('message', function(event) {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
